version: '2.2'
services:
    mysql:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: blockflix
        MYSQL_DATABASE: blockflix_development
        MYSQL_USER: blockflix
        MYSQL_PASSWORD: blockflix

    blockflix:
      image: blockflix:latest
      restart: always
      volumes:
          - .:/opt/blockflix
      environment:
          - MYSQL_DATABASE=blockflix_development
          - MYSQL_USER=blockflix
          - MYSQL_PASSWORD=blockflix
          - MYSQL_HOST=mysql
          - FLASK_APP=autoapp.py
          - FLASK_DEBUG=1
      depends_on:
          - mysql
      ports:
          - "5000:5000"
